#!/usr/bin/env python

import  notify2 ,os , random, time, json
notify2.init('test service')
home_path = '/home/salar'

path = '{}/Pictures/wallpaper/'.format(home_path)

pics = []
for root , directory , files in os.walk(path):
    pics = files
chosen_pic = random.choice(pics)
choice = path + '\"{}\"'.format(chosen_pic)
os.system('wal -i {} '.format(choice))
#os.system('feh --bg-scale {} &'.format(choice))
CONKY_IN = '/home/salar/.config/wal/all.conkyrc'
CONKY_OUT = '/home/salar/.cache/wal/all.conkyrc'
COLORS = '/home/salar/.cache/wal/colors.json'

with open(CONKY_IN,'r') as f:
    data = f.read()
with open(COLORS, 'r') as f:
    colors = json.loads(f.read())['colors']

for key, value in colors.items():
    data = data.replace('__'+key, f'\'{value}\'')

with open(CONKY_OUT, 'w') as f:
    f.write(data)
    
#os.system('rm -f {}/.themes/my_openbox/openbox-3/themerc'.format(home_path))
#os.system('cp {}/.cache/wal/themerc {}/.themes/my_openbox/openbox-3/themerc'.format(home_path,home_path))
#os.system('openbox --reconfigure')
#
os.system('killall tint2')
os.system('tint2 -c {}/.cache/wal/tint2rc &'.format(home_path))

n = notify2.Notification('background and colorscheme changed with : {}'.format(chosen_pic))
n.show()
